# .github/workflows/update-readme.yml
name: Update README

on:
  push:
    branches: [ main, master ]
    paths: 
      - '**/*.md'
      - '!README.md'
  pull_request:
    branches: [ main, master ]
    paths: 
      - '**/*.md'
      - '!README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-frontmatter
    
    - name: Update README
      run: python scripts/update_readme.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Auto-update README.md"
        git push
